spring.application.name=spotme
spring.datasource.url=jdbc:postgresql://localhost:5432/spotme
spring.datasource.username=spotme_user
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
jwt.secret=${JWT_SECRET}
